<?php

namespace App\Repository\Equipe;

/**
 * EquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function byActiveSaison()
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.saison','s')
            ->where('s.active = :active')
            ->setParameter('active', true )
            ->leftJoin('e.categorie','c')
            ->orderBy('c.hierarchie','asc');
        return $qb->getQuery()->getResult();
    }

    public function bySaison($saison)
    {
        $qb = $this->createQueryBuilder('e')
            ->where('e.saison = :saison')
            ->setParameter('saison', $saison)
            ->leftJoin('e.categorie','c')
            ->orderBy('c.hierarchie','asc');
        return $qb->getQuery()->getResult();
    }

}
