<?php

namespace App\Repository\Equipe;

/**
 * RefCompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefCompetitionRepository extends \Doctrine\ORM\EntityRepository
{
}
