liip_imagine:
    resolvers:
        default:
            web_path: ~

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets :
        cache : ~

        produitThumb :
            quality : 80
            filters :
                thumbnail  : { size : [250,250], mode : outbound }
        produit :
            quality : 75
            filters :
                thumbnail  : { size : [500,500], mode : outbound }
        blog :
            quality : 80
            filters :
                thumbnail  : { size : [800,800], mode : inset }
        blogSidebar :
            quality : 80
            filters :
                thumbnail  : { size : [100,100], mode : inset }