<?php

namespace App\Repository\Blog;

use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategorie($slug)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.categories','c')
            ->addSelect('c')
            ->where('c.slug = :slug')
            ->orderBy('a.createdAt', 'ASC')
            ->setParameter('slug' , $slug);
        return $qb->getQuery()->getResult();
    }

    public function findAllActu()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->orderBy('a.createdAt', 'DESC');
        return $qb->getQuery()->getResult();
    }

    public function ActuSidebar()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->orderBy('a.createdAt', 'DESC')
        ->setFirstResult(0)
        ->setMaxResults(10);

        return new Paginator($qb);
    }
}
