<?php

namespace App\Repository;

/**
 * TvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesFranceRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCodePostal($cp)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.villeCodePostal = :cp')
            ->setParameter('cp', $cp);
        return $qb->getQuery()->getResult();
    }
}