<?php

namespace App\Repository\Ecommerce;

/**
 * QuantiteProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
}
