<?php

namespace App\Repository\Ecommerce;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvaRepository extends \Doctrine\ORM\EntityRepository
{

}
