<?php

namespace App\Repository\Import;

/**
 * FichierLicencieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierLicencieRepository extends \Doctrine\ORM\EntityRepository
{
}
