<?php

namespace App\Repository\Import;

/**
 * ImportMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
