<?php

namespace App\Repository\Event;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function allEvents()
    {
        return $this->createQueryBuilder('e')
            ->orderBy('e.createdAt','DESC')
            ->getQuery()
            ->getResult();
    }
}
