<?php

namespace App\Repository\Event;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function  getRervationsByEvent($evenement)
    {
        $id = $evenement->getId();
        $query = $this->createQueryBuilder('r')
            ->where('r.evenement = :id')
            ->setParameter(':id', $id)
            ->orderBy('r.createdAt', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
