<?php

namespace App\Repository\Match;

/**
 * MatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchRepository extends \Doctrine\ORM\EntityRepository
{
    public function menuMatchs()
    {
        $qb = $this->createQueryBuilder('m')
            ->addOrderBy('m.date','desc');
        return $qb->getQuery()->getResult();
    }
}
