<?php

namespace App\Repository\Core\Bureau;

/**
 * FicheBureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheBureauRepository extends \Doctrine\ORM\EntityRepository
{
}
