<?php

namespace App\Repository\Core\Bureau;

/**
 * FicheBureauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheBureauRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBureauWithActiveSaison()
    {
        $query = $this->createQueryBuilder('f')
            ->leftJoin('f.saison', 'saison')
            ->addSelect('saison')
            ->leftJoin('f.fonctions', 'fonctions')
            ->addSelect('fonctions')
            ->where('saison.active = :active')
            ->setParameter('active' , true)
            ->orderBy('fonctions.hierarchie','ASC')
            ->getQuery();

        return $query->getResult();
    }

}

