<?php

namespace App\Repository\Core;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMonClub()
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.monclub = :monClub')
            ->setParameter('monClub', true )
            ->getQuery();

        return $query->getResult();
    }

    public function getConventionClub()
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.convention = :convention')
            ->setParameter('convention', true )
            ->getQuery();

        return $query->getResult();
    }

    public function findAllClubs()
    {
        $query = $this->createQueryBuilder('c')
            ->OrderBy('c.numeroFederal','ASC')
            ->getQuery();

        return $query->getResult();
    }
}
