<?php

namespace App\Repository\Core;

/**
 * ClubLogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubLogoRepository extends \Doctrine\ORM\EntityRepository
{
}
