<?php

namespace App\Repository\Core;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EntrainementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrainementRepository extends \Doctrine\ORM\EntityRepository
{
    public function byActiveSaison()
    {
        $qb = $this->createQueryBuilder('e')
            ->leftJoin('e.saison','s')
            ->where('s.active = :active')
            ->setParameter('active', true )
            ->leftJoin('e.jourEntrainement','j')
            ->orderBy('j.tri','asc')
            ->addOrderBy('e.horaireDebut','asc');
        return $qb->getQuery()->getResult();
    }

    public function bySaison($saison)
    {
        $qb = $this->createQueryBuilder('e')
            ->where('e.saison = :saison')
            ->setParameter('saison', $saison)
            ->leftJoin('e.jourEntrainement','j')
            ->orderBy('j.tri','asc')
            ->addOrderBy('e.horaireDebut','asc');
        return $qb->getQuery()->getResult();
    }

    public function findUpdate()
    {
        $query = $this->createQueryBuilder('e')
            ->orderBy('e.updatedAt', 'desc')
            ->setFirstResult(0)
            ->setMaxResults(1);

        return new Paginator($query);
    }
}
