<?php

namespace App\Repository\Core;

/**
 * SponsorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgSponsorsRepository extends \Doctrine\ORM\EntityRepository
{
}
