<?php

namespace App\Repository\Core;

/**
 * LicencieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencieRepository extends \Doctrine\ORM\EntityRepository
{
}
